FROM gcr.io/deeplearning-platform-release/base-cpu

RUN apt-get update \
  && apt-get install -y \
    vim \
    node-gyp \
    nodejs-dev \
    libssl1.0-dev \
    npm \
    nodejs

RUN pip install jupyterhub-dummyauthenticator

RUN pip install --upgrade pip \
  && pip install --upgrade \
    jupyterhub

RUN npm install -g configurable-http-proxy

# Install Dataproc Spawner
COPY setup.py /tmp/dataprocspawner/setup.py
COPY dataprocspawner/ /tmp/dataprocspawner/dataprocspawner/
COPY dataprochub/ /tmp/dataprocspawner/dataprochub/
RUN pip install git+https://github.com/GoogleCloudPlatform/jupyterhub-gcp-proxies-authenticator
RUN pip install /tmp/dataprocspawner/

# JupyterHub design
COPY static/templates/ /etc/jupyterhub/templates/

COPY examples/docker/jupyterhub_config_example.py ./jupyterhub_config.py

EXPOSE 8080

ENTRYPOINT ["jupyterhub"]